[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
chrono = "0.4.41"
secp256k1 = { version = "0.31.0", features = ["global-context", "rand"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10"
